name: .NET

on:
  push:
    branches: [ master ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build:
    name: test-${{matrix.os}}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        dotnet-version: [ '6.0.x' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal